- hosts: localhost

  tasks:

    - name: Copying files and dirs out to the Ansible directory
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        preserve: yes
      with_items:
        - {src: /REPOS/ANSIBLE/ansible.cfg, dest: /ANSIBLE/ansible.cfg}
        - {src: /REPOS/ANSIBLE/main.yml, dest: /ANSIBLE/main.yml}
        - {src: /REPOS/ANSIBLE/roles, dest: /ANSIBLE/roles}
        - {src: /REPOS/ANSIBLE/inventory, dest: /ANSIBLE/inventory}
