- hosts: localhost

  tasks:

    - name: Copying files and dirs out to the Ansible directory
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
        mode: preserve
      with_items:
        - {src: /tmp/ANSIBLE/ansible.cfg, dest: /ANSIBLE/ansible.cfg}
        - {src: /tmp/ANSIBLE/main.yml, dest: /ANSIBLE/main.yml}
        - {src: /tmp/ANSIBLE/roles, dest: /ANSIBLE/}
        - {src: /tmp/ANSIBLE/inventory, dest: /ANSIBLE/}
